apiVersion: v1
kind: ConfigMap
metadata:
  name: pop-webapp-cm
  namespace: popgroup
  labels:
    env: prod
    app: pop-webapp
data:
  odoo_url: http://192.168.1.83:30010
  pgadmin_url: http://192.168.1.83:30011