apiVersion: v1
kind: Service
metadata:
  name: pop-webapp-svc
  namespace: popgroup
  labels:
    env: prod
    app: pop-webapp
spec:
  selector:
    app: pop-webapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30012
  type: NodePort