---
- name: Apply Kubernetes manifests file
  hosts: localhost
  tasks:
    - name: Apply Kubernetes manifests
      command: "kubectl --kubeconfig={{ playbook_dir }}/k3s/kubeconfig.yml apply -k {{ playbook_dir }}/../../kubernetes --validate=false --insecure-skip-tls-verify"

    # - name: Apply Kubernetes manifests
    #   command: "kubectl --kubeconfig={{ playbook_dir }}/k3s/kubeconfig.yml delete -k {{ playbook_dir }}/../../kubernetes --insecure-skip-tls-verify"