apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  namespace: popgroup
  labels:
    env: prod
    type: local
    app: pgadmin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data-pgadmin