apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: popgroup
  labels:
    env: prod
    app: pgadmin
    type: local
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce