services:
  database:
    container_name: odoo_database
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=pwdodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  web:
    image: odoo:17.0
    container_name: odoo_web
    depends_on:
      - database
    ports:
      - "8069:8069"
    environment:
      - HOST=database
      - USER=odoo
      - PASSWORD=pwdodoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
volumes:
  odoo-web-data:
  odoo-db-data: