services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@webapp.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - 80:80