apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: popgroup
  labels:
    env: prod
    app: postgres
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce