apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: popgroup
  labels:
    env: prod
    type: local
    app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /data-postgres