---
# Récupère le fichier /etc/rancher/k3s/k3s.yaml depuis le server kubenetes approvisionné par térraform précédement
- name: Retrieve kubeconfig file
  hosts: k3s
  tasks:
    - name: Copy file kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: $PWD/ansible/kubeconfig/kubeconfig
        flat: yes
    
    - name: Modify kubeconfig
      local_action:
        module: lineinfile
        path: $PWD/ansible/kubeconfig/kubeconfig
        regexp: '^    server: https://127.0.0.1:6443'
        line: '^    server: https://{{ ansible_host }}:6443'