---
- name: docker_deploy
  hosts: docker
  become: true
  # include_vars:
  #   file: "host_vars/docker.yaml"
  vars:
    network: pop-network
  roles:
    - docker
    - pop-webapp
    - odoo
    - pgdamin