apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
  namespace: popgroup
  labels:
    env: prod
    type: local
    app: odoo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /data-odoo

