apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  namespace: popgroup
  labels:
    app: odoo
    env: prod
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:17.0
        env:
        - name: USER
          valueFrom:
            configMapKeyRef:
              key: user
              name: odoo-cm
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: odoo-secret
        - name: HOST
          valueFrom:
            configMapKeyRef:
              key: host
              name: odoo-cm
        ports:
        - containerPort: 8069
        volumeMounts:
        - name: odoo-persistent-storage
          mountPath: /var/lib/odoo
        - name: odoo-persistent-storage-odoo
          mountPath: /etc/odoo
        - name: odoo-persistent-storage-extras
          mountPath: /mnt/extra-addons
      volumes:
      - name: odoo-persistent-storage
        persistentVolumeClaim:
          claimName: odoo-pvc
      - name: odoo-persistent-storage-odoo
        hostPath:
          path: /data-odoo/config
      - name: odoo-persistent-storage-extras
        hostPath:
          path: /data-odoo/addons