---
# tasks file for odoo
- name: generate docker compose
  template:
    src: "odoo-compose.yaml.j2"
    dest: /home/{{ ansible_user }}/odoo-compose.yml
    mode: '0555'

- name: start odoo stack
  command: "docker-compose -f /home/{{ ansible_user }}/odoo-compose.yml up -d"